### PR TITLE
Disable grid item width options when using flex-basis

### PR DESCRIPTION
**Pull request by tomusborne**
This PR disables the width field/slider if we're using the Flex Basis option.

It's a bit of a logic minefield..

We want to:

1. Disable the width options across all lower devices if flex basis is set
2. Allow the width option on those lower devices if flex-basis is set manually to "auto"

See discussion here for more context: https://edge22studios.slack.com/archives/C023546D3QR/p1630528829016900?thread_ts=1630512448.010400&cid=C023546D3QR

### CODE REVIEW

**Comment by JeanPaiva** [comment]
It works as expected, but I can add anything to `basis` field. Maybe we can change to a select field?
Screenshot 2021-09-02 193404

**Comment by tomusborne** [comment]
Hmm, it can be any percentage or "auto". Maybe it just needs some basic sanitizing to allow numbers, decimals and lowercase characters?

**Comment by JeanPaiva** [comment]
Ye could help, just to not be so open.

**Comment by tomusborne** [comment]
Visual validation looks pretty complex - surprised it's not a core thing. For now I think the above should do the trick. We should look into adding our own validation method that's better for users in the future.

**Review by JeanPaiva — APPROVED** [review]
It works as expected. If the user does a typo it will remove the full string. We may need to improve the input field in the future to allow better feedback for users.

**Pull request merged**
