### PR TITLE
Error when editing widget in the customizer

### LINKED ISSUE #76: Error when editing widget in the customizer when GB is activated.
### Description
When GB is activated, this error shows when editing widgets in the customizer and unable to save:
"An error has occurred. Please reload the page and try again."

No issue in Dashboard > Widget.

### Steps to reproduce
1. Activate GB and go to Customizer > Widget and edit any widgets.

#### Expected behavior
Save the widgets properly.

#### Actual behavior
Widgets are not being saved properly.

#### References: 
https://www.screencast.com/t/CVZO4uTJ

### PR DESCRIPTION
**Pull request by JeanPaiva**
Closes #76

### CODE REVIEW

**Comment by tomusborne** [comment]
Testing this. It fixes the error in the classic widget editor and successfully rebuilds the CSS files in the `widgets.php` area, but it doesn't rebuild them when saved in the Customizer. Must be a best of both worlds somehow..

**Comment by tomusborne** [comment]
Ah, this doesn't rebuild the CSS when using the Customizer block widget area even without the checks. I guess the `widget_update_callback` isn't used in the same way in the Customizer.

Maybe we also need to rebuild CSS files in `customize_save_after`.

**Comment by tomusborne** [comment]
Ok, so focuses on this specific bug, maybe we should do this?:

    if ( function_exists( 'wp_use_widgets_block_editor' ) && wp_use_widgets_block_editor() ) {
        update_option( 'generateblocks_dynamic_css_posts', array() );
    }

Benefits:

1. Won't cause the error in the classic Customizer widget editor.
2. Won't trigger a CSS file rebuild in in the classic widgets.php editor.
3. Does trigger a CSS file rebuild in the widgets.php block editor.

Then we'll deal with the Customizer not triggering a rebuild in a separate PR.

**Review by JeanPaiva — COMMENTED** [review]
All good.

**Pull request merged**
