### PR TITLE
Remove desktop autoWidth

### PR DESCRIPTION
**Pull request by tomusborne**
This removes the "Auto" option from the grid item width on desktop.

This is no longer needed once we remove the default value (https://github.com/tomusborne/generateblocks/pull/92), as the user can simply clear the width value to achieve an "auto" width.

We've left the "Auto" option on tablet and mobile as those actually output an `auto` property value to override the parent.

### CODE REVIEW

**Comment by JeanPaiva** [comment]
We might want to keep this PR, in #92 branch I couldn't clear the width value properly.

**Comment by tomusborne** [comment]
Working on a PR for that today.

**Comment by tomusborne** [comment]
@JeanPaiva this good to go now?

**Review by JeanPaiva — APPROVED** [review]
All good.

**Pull request merged**
