### PR TITLE
Update wp packages

### PR DESCRIPTION
**Pull request by JeanPaiva**
Updating the packages. Also, I'm now forcing versions, since the packages are updated very frequently by the core team, sometimes patches can break on new `npm install` this way we are always using exact same version. We must keep updating these packages on every major version.

### CODE REVIEW

**Review by tomusborne — APPROVED** [review]
Good idea, much prefer having to manually change version numbers.

**Comment by JeanPaiva** [comment]
@tomusborne PR is ready. Updated the @wordpress/scripts package and I fixed a bunch of lint issues.

**Comment by tomusborne** [comment]
Looks good to me! `@emotion/react` instead of just `react`?

**Comment by JeanPaiva** [comment]
I think there were errors on build/start cause this package was not found

**Pull request merged**
