### PR TITLE
Feature: Only show one dimension field if synced

### PR DESCRIPTION
**Pull request by tomusborne**
This makes it so only one dimension field displays if all 4 sides are synced.

### CODE REVIEW

**Review by JeanPaiva — APPROVED** [review]
One thing that I noticed is that when you are on the tablet device and change to mobile, the sync persists. Not sure if it was intentional or not. Apart from that all good.

**Comment by tomusborne** [comment]
Hmm, I would say not intentional. Tried to make it so it only auto-syncs if the values all exist and are the same. Seems the component isn't re-rendering from tablet -> mobile.

**Comment by tomusborne** [comment]
@JeanPaiva what about the latest commit?

**Comment by JeanPaiva** [comment]
Another one:

When syncing on the desktop and going to the tablet, the placeholder is only showing for the top side.

Screenshot 2023-06-02 at 12 15 01

**Comment by tomusborne** [comment]
@JeanPaiva this is using the latest pull?

**Comment by JeanPaiva** [comment]
@tomusborne all good now.

**Pull request merged**
