### PR TITLE
Fix container tag name accepting any value

### PR DESCRIPTION
**Pull request by JeanPaiva**
This adds a tag name attribute validation allowing only the defined tags.

### CODE REVIEW

**Comment by tomusborne** [comment]
Works well! Seeing a couple of JSLint issues though.

jslint

**Comment by JeanPaiva** [comment]
@tomusborne fixed!

**Comment by tomusborne** [comment]
One issue I found is GB Pro doesn't actually filter the list of available tagnames - `a` isn't an option to choose from, the plugin does it for you if you enable container links.

So checking the list of tag names failed when it was set to `a`, as it's not an option in the select.

Last commit I did there was to introduce a new list of allowed tag names just like we have on the frontend. Might be a better way? Not sure.

**Comment by JeanPaiva** [comment]
@tomusborne I liked. Just removed the `map` function and I think we are good to go now!

**Review by tomusborne — APPROVED** [review]

**Pull request merged**
