### PR TITLE
Prevent grid item zero values or values that start with zero

### PR DESCRIPTION
**Pull request by tomusborne**
This prevents users from setting a `0%` width for grid items.

It also tightens up the UI a little by placing the slider inside the `BaseControl`.

### CODE REVIEW

**Review by JeanPaiva — APPROVED** [review]
All good.
Quick note: Users are still allowed to use fractional numbers. Eg. `.2`

**Comment by tomusborne** [comment]
Hmm, think we should prevent that in the `startsWith` check as well? Might be a good idea.

**Comment by JeanPaiva** [comment]
@tomusborne but doing so are we not deciding for the user that it should not use these small fractions of size? Not sure of a use case for this, but do we have issues allowing them to use this?

**Comment by tomusborne** [comment]
Can't think of a good reason not to allow it. Not allowing 0 makes sense, but if a user needs to set `.1` then they can.

**Pull request merged**
