### PR TITLE
Feature: Improve typography component

### PR DESCRIPTION
**Pull request by tomusborne**
This PR:

1. Adds the container text alignment options to the Typography panel.
2. Adds the headline text alignment options to the Typography panel
3. Fixes a bug where Google fonts were duplicated in the font family dropdown
4. Improves the UI of the typography panel.

typography2

### CODE REVIEW

**Review by JeanPaiva — COMMENTED** [review]
Font family improvements are good.

Text alignment, why only for the containers? Even though we have it on inspectors' controls, I think having it in the toolbar is still necessary to keep consistency with other blocks.

Too much whitespace to the right, maybe having the label to the left could save some vertical space and remove that white box. Maybe we can add more controls there like bold, italic, and strikethrough?

Also, why don't we have "justify"?

**Comment by tomusborne** [comment]
> Text alignment, why only for the containers? Even though we have it on inspectors' controls, I think having it in the toolbar is still necessary to keep consistency with other blocks.

We can/should do the same for Headline. Button doesn't have an alignment option, but it should. Moving from toolbar to inspector controls was discussed on Monday. David had mentioned it was confusing users as it wasn't obvious that the control was available for all devices.

Agree on whitespace, let me see if I can do something there.

Justify is a good one to add - any other alignments?

**Comment by tomusborne** [comment]
@JeanPaiva 

1. Fixed the whitespace
2. Added justify
3. Kept the block toolbar controls

Will add alignment to the Button block in a separate PR as it involves some migration.

**Review by JeanPaiva — APPROVED** [review]

**Comment by onetrev** [comment]
Hey @tomusborne ... I didn't want to create a new issue, but I noticed @JeanPaiva mentioned adding italic, strikethrough, etc. 

If this were added then you could have italics and strikethrough for example for **dynamic data blocks**.  You can't do with GenerateBlocks because there is no GUI option for it. But you can do that currently with WP Core Blocks, like the Post Date block, see screenshot below. 

Screenshot 2023-03-04 195910

I did a poor job of explaining [the issue](https://github.com/tomusborne/generateblocks/issues/697) previously. I understand you can't highlight specific words to be italic / strikethrough, but the whole block should be able to be italic or strikethrough right?

Happy to make a new issue for this if it's something you guys think you'd add one day. :)

**Pull request merged**
